create or replace TABLE ARUNA.{{ ENV }}_TEST_SCHEMA.SALES_DATA (
	SALES_ID NUMBER(38,0),
	CUSTOMER_NAME VARCHAR(16777216),
	TRANSACTION_ID NUMBER(38,0),
	TRANSACTION_DATE DATE,
	AMOUNT FLOAT
);


create or replace view ARUNA.TEST_SCHEMA.V_{{ ENV }}_SALES_DATA (
	SALES_ID,
	CUSTOMER_NAME,
	TRANSACTION_ID,
	TRANSACTION_DATE,
	AMOUNT
)
AS
SELECT * FROM ARUNA.TEST_SCHEMA.SALES_DATA;
