name: Liquibase Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install and Configure Liquibase
        run: |
          wget https://github.com/liquibase/liquibase/releases/download/v4.18.2/liquibase-4.18.2.tar.gz
          tar -xzf liquibase-4.18.2.tar.gz
          export PATH=$PATH:$PWD/liquibase

      - name: Execute Liquibase Update
        run: |
          liquibase --changeLogFile=path/to/changelog.xml --defaultsFile=path/to/liquibase.properties update
