name: SNOWCHANGE

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'sf/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
  runs-on: ubuntu-latest

steps:
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
- name: Checkout repository
  uses: actions/checkout@v2

- name: Use Python 3.8.x
  uses: actions/setup-python@v2.2.1\
  with:
    python-version: 3.8.x

- name: Run schemachange
  env:
    SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
    SNOWFLAKE_USERNAME: ${{ secrets.SF_USERNAME }}
    SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
    SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
    SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
    SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}

run: |
echo "GITHUB_WORKSPACE: arunanew"
  python --version
echo "Step 1: Installing schemachange"
  pip install schemachange
echo "Step 2: Running schemachange"
schemachange -f arunanew/sf -a xanykag-kq15501 -u ARUNA1208 -r ACCOUNTADMIN -w COMPUTE_WH -d ARUNA -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-sales-data-table
# to reference files in your repository
# to reference files in your repository
